name: actualisation du serve

on:
  push:
    branches: [ dev ]

jobs:
  actualisation:

    runs-on: ubuntu-latest

    steps:
    - name: pull
      run: git pull origin dev
    - name: composer update
      run: composer update
    - name: npm update
      run: npm update
