name: actualisation du projet sur serveur de dev

on:
  push:
    branches: [ Dev ]

jobs:

  # Création de l'environnement virtuel
  creation_ssh:
    name: "Création de l'environnement virtuel pour la connexion en SSH avec le serveur"

    runs-on: ubuntu-latest

    steps:
      - name: "Configuration SSH de la machine virtuelle"
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_rsa.key
          chmod 600 ~/.ssh/id_rsa.key
          cat >>~/.ssh/config <<END
            Host projetcube
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/id_rsa.key
              StrictHostKeyChecking no
          END

      - name: "Connexion au serveur de prod et git pull"
        run: |
          ssh projetcube 'cd /var/www/html/cube1 && git fetch && git pull'
      #- name: test back
      #- name: test flutter
